### ISSUE TITLE
Not all APIs have rate limits

### ISSUE THREAD

**Issue by dstufft** [brettcannon/gidgethub#25]
When working with the integrations API, I noticed that not all APIs have rate limits, which causes gidgethub to fail hard:

```
Traceback (most recent call last):
  File "/Users/dstufft/.virtualenvs/browntruck/lib/python3.6/site-packages/twisted/internet/defer.py", line 459, in callback
    self._startRunCallbacks(result)
  File "/Users/dstufft/.virtualenvs/browntruck/lib/python3.6/site-packages/twisted/internet/defer.py", line 567, in _startRunCallbacks
    self._runCallbacks()
  File "/Users/dstufft/.virtualenvs/browntruck/lib/python3.6/site-packages/twisted/internet/defer.py", line 653, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/Users/dstufft/.virtualenvs/browntruck/lib/python3.6/site-packages/twisted/internet/defer.py", line 1357, in gotResult
    _inlineCallbacks(r, g, deferred)
--- <exception caught here> ---
  File "/Users/dstufft/.virtualenvs/browntruck/lib/python3.6/site-packages/twisted/internet/defer.py", line 1301, in _inlineCallbacks
    result = g.send(result)
  File "t.py", line 46, in inner
    async for installation in gh.getiter("/integration/installations"):
  File "/Users/dstufft/.virtualenvs/browntruck/src/gidgethub/gidgethub/abc.py", line 64, in getiter
    authorization)
  File "/Users/dstufft/.virtualenvs/browntruck/src/gidgethub/gidgethub/abc.py", line 48, in _make_request
    data, self.rate_limit, more = sansio.decipher_response(*response)
  File "/Users/dstufft/.virtualenvs/browntruck/src/gidgethub/gidgethub/sansio.py", line 267, in decipher_response
    return data, RateLimit.from_http(headers), _next_link(headers.get("link"))
  File "/Users/dstufft/.virtualenvs/browntruck/src/gidgethub/gidgethub/sansio.py", line 211, in from_http
    limit = int(headers["x-ratelimit-limit"])
builtins.KeyError: 'x-ratelimit-limit'
```

**Comment by brettcannon** [comment]
Great, so their docs are lying that "[any API request](https://developer.github.com/v3/#rate-limiting)" will have the rate limit headers.

**Comment by dstufft** [comment]
@brettcannon it's possible it is a bug that this API doesn't have it, the entire integrations API is early preview right now.

**Comment by brettcannon** [comment]
Sure, but then the question becomes do we work around their bug or prevent you from using the integrations API for now? Both are sucky options.

**Comment by eliot1019** [comment]
I am not seeing ratelimits on github api requests on my github enterprise account. There needs to a be a safe way to support this change.

**Comment by brettcannon** [comment]
Probably if you update

https://github.com/brettcannon/gidgethub/blob/4d5819cf50f3ad896713364d5e749bea466b9f05/gidgethub/sansio.py#L233-L234

to catch the `KeyError` and return `None` instead that should do it (plus tests and docs, of course). If anyone wants to provide a PR I will happily review it.

**Comment by brettcannon** [comment]
[ @eliot1019 edited your message ⬆️ to come off as more 😃 and less 😠 ]
