### ISSUE TITLE
GitHubAPI.delete() doesn't accept "data" keyword argument?

### ISSUE THREAD

**Issue by Mariatta** [brettcannon/gidgethub#52]
In CPython, we're trying to dismiss review requests from invalid PRs.
It was implemented in python/bedevere#96.

GitHub API for deleting review requests is documented here: https://developer.github.com/v3/pulls/review_requests/#delete-a-review-request

In bedevere, the code looks like the following:

```
await gh.delete("https://api.github.com/repos/python/cpython/pulls/6130/requested_reviewers",
    data={'reviewers': ['gpshead', '1st1', 'asvetlov', 'ericvsmith', 'rhettinger', 'gvanrossum', 'ilevkivskyi', 'skrah', 'terryjreedy'], 'team_reviewers': ['windows-team', 'email-team']}
```

That caused exception from gidgethub:
```
2018-03-17T16:35:10.426350+00:00 app[web.1]: GH delivery ID 5133c800-29a9-11e8-856e-fd01f7530d5e
2018-03-17T16:35:11.428012+00:00 heroku[router]: at=info method=POST path="/" host=bedevere.herokuapp.com request_id=5525ec4a-12e0-4806-b436-fdbf125aeff0 fwd="192.30.252.35" dyno=web.1 connect=0ms service=1005ms status=500 bytes=187 protocol=https
2018-03-17T16:35:11.427163+00:00 app[web.1]: Traceback (most recent call last):
2018-03-17T16:35:11.427214+00:00 app[web.1]:   File "/app/bedevere/__main__.py", line 37, in main
2018-03-17T16:35:11.427216+00:00 app[web.1]:     await router.dispatch(event, gh)
2018-03-17T16:35:11.427238+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gidgethub/routing.py", line 80, in dispatch
2018-03-17T16:35:11.427254+00:00 app[web.1]:     await callback(event, *args, **kwargs)
2018-03-17T16:35:11.427260+00:00 app[web.1]:   File "/app/bedevere/close_pr.py", line 47, in dismiss_invalid_pr_review_request
2018-03-17T16:35:11.427263+00:00 app[web.1]:     data=data)
2018-03-17T16:35:11.427309+00:00 app[web.1]: TypeError: delete() got an unexpected keyword argument 'data'
```

The other coroutines, `post()`, `put()`, `patch()` all accept the `data` keyword argument. Perhaps delete should too?

https://github.com/brettcannon/gidgethub/blob/d54d2948a3bab93e54f283886b4edf483340f52f/gidgethub/abc.py#L107-L108

**Comment by brettcannon** [comment]
Probably. If I remember correctly when I looked at various DELETE calls I couldn't find one that required a data payload so I simply left it out. So I guess it's time to add one! 😄
